const items = [
  {
    id: "1",
    title: "Asus Laptop",
    rating: "4.5",
    price: 2244,
    originalPrice: 2799,
    description:
      "Asus Laptop with 1 TB storage, perfect for high-performance computing and gaming. Sleek design with fast processing speeds for work or entertainment.",
    image: require("@/assets/images/laptop.png"),
    discount: 0.4,
    reviews: "117 reviews",
    variant: ["Silver", "Black", "White"],
    category: "Laptops",
  },
  {
    id: "2",
    title: "Sony Headphone",
    rating: "4.7",
    price: 132,
    originalPrice: 1099,
    description:
      "High-quality Sony headphones with crystal clear sound and deep bass. Ideal for music lovers and audiophiles. Blue color adds a stylish touch.",
    image: require("@/assets/images/headphone.png"),
    discount: 0.5,
    reviews: "234 reviews",
    variant: ["Blue", "Red", "Black"],
    category: "Headphones",
  },
  {
    id: "3",
    title:
      "Sony Playstation 5 Official Dual Sense Controller Marvel's Spider Man 2 Limited Edition (Pre-owned)",
    rating: "4.3",
    price: 60,
    originalPrice: 75,
    description:
      "Experience the thrill of gaming with the limited edition Marvel's Spider Man 2 DualSense controller for PlayStation 5. Pre-owned but in excellent condition.",
    image: require("@/assets/images/ps51.png"),
    discount: 0.3,
    reviews: "87 reviews",
    variant: ["Green", "Red"],
    category: "Gaming Accessories",
  },
  {
    id: "4",
    title: "iPhone 16",
    rating: "4.1",
    price: 700,
    originalPrice: 1099,
    description:
      "The iPhone 16 brings next-level performance with the latest A-series chip, advanced camera systems, and a sleek design. Perfect for gaming, photography, and productivity.",
    image: require("@/assets/images/iphone.png"),
    discount: 0.2,
    reviews: "512 reviews",
    variant: ["64GB", "128GB", "256GB", "512GB"],
    category: "Smartphones",
  },
  {
    id: "5",
    title: "LG 45 inch 21:9 Ultragear™ OLED WQHD 800R Curved Gaming Monitor",
    rating: "4.8",
    price: 1499,
    originalPrice: 1799,
    description:
      "A stunning 45-inch OLED curved gaming monitor with WQHD resolution and 800R curvature, delivering immersive gameplay and ultra-smooth visuals.",
    image: require("@/assets/images/lg.png"),
    discount: 0.17,
    reviews: "205 reviews",
    variant: ["Black"],
    category: "Monitors",
  },
  {
    id: "6",
    title: "Finalmouse Ultralight X - ULX Prophecy SCREAM",
    rating: "4.6",
    price: 189,
    originalPrice: 250,
    description:
      "A high-performance gaming mouse designed for esports professionals, offering ultra-lightweight construction and precision tracking.",
    image: require("@/assets/images/final.png"),
    discount: 0.24,
    reviews: "89 reviews",
    variant: ["White", "Black"],
    category: "Gaming Accessories",
  },
  {
    id: "7",
    title: "Samsung S24 Ultra 5G 256 GB",
    rating: "4.9",
    price: 1199,
    originalPrice: 1399,
    description:
      "Samsung's latest flagship smartphone with a powerful processor, stunning camera system, and a 120Hz AMOLED display. A true powerhouse in mobile technology.",
    image: require("@/assets/images/Samsung.png"),
    discount: 0.14,
    reviews: "678 reviews",
    variant: ["256GB", "512GB"],
    category: "Smartphones",
  },
  {
    id: "8",
    title: "Keychron V1 QMK/VIA Custom Mechanical Keyboard",
    rating: "4.5",
    price: 129,
    originalPrice: 149,
    description:
      "A versatile custom mechanical keyboard featuring QMK/VIA support, hot-swappable switches, and a premium build for an outstanding typing experience.",
    image: require("@/assets/images/Keychron.png"),
    discount: 0.13,
    reviews: "321 reviews",
    variant: ["Red Switch", "Blue Switch", "Brown Switch"],
    category: "Keyboards",
  },
];

export default items;
